Added mocha and chai
emiliagorskaa/blog-backend pull request #1
Opened 2023-01-16 10:40 UTC by emiliagorskaa

Added mocha and chai testing to the project

2023-01-17 14:41 UTC, Melodija requested changes

2023-01-17 14:41 UTC, Melodija commented on config.env
> +ATLAS_URI="mongodb+srv://emiliagorska:CAvAL5TDf7RulgrL@blog-project-cluster.ppoy2d6.mongodb.net/?retryWrites=true&w=majority"
This should be in your .gitignore file :) Otherwise anyone viewing your repo will be able to access your database.
I would add this to your .env file and ensure it's in your .gitignore file and ensure that the key you're using in this URL has been changed.

2023-01-17 14:41 UTC, Melodija commented on test/endpoints.test.js
> +        // console.log("RES", res);
Might be worth cleaning up old console logs and comments that don't make sense. Obviously keep the important ones for future reference but these ones can be tidied up.

2023-01-25 14:17 UTC, emiliagorskaa commented on config.env
> +ATLAS_URI="mongodb+srv://emiliagorska:CAvAL5TDf7RulgrL@blog-project-cluster.ppoy2d6.mongodb.net/?retryWrites=true&w=majority"
done

2023-01-25 14:17 UTC, emiliagorskaa commented on test/endpoints.test.js
> +        // console.log("RES", res);
done

2023-04-21 13:45 UTC, merged